#!/bin/sh
# fluxbox startup file
#
# By this point, X has called startfluxbox.
# The goal of this file is to:
#
# * set a custom fluxbox environment
# * start apps before starting fluxbox
# * start fluxbox

# Inform GNOME of window manager.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
    dbus-send --print-reply --session \
              --dest=org.gnome.SessionManager "/org/gnome/SessionManager" \
              org.gnome.SessionManager.RegisterClient "string:fluxbox-gnome" \
              "string:$DESKTOP_AUTOSTART_ID"
fi

# Set a solid black background.
fbsetroot -solid black

xset +fp "$HOME"/.local/share/fonts
xset fp rehash

xrdb -merge "$HOME"/.Xresources
xset r rate 250 30

thunar --daemon &
xfce4-power-manager &
killall -u $(id -un) parcellite; parcellite &

/usr/lib/x86_64-linux-gnu/indicator-sound/indicator-sound-service &
pnmixer &

screens &

bash -s - <<EOF &
sleep 5
killall -u $(id -un) \
    gnome-screensaver \
    gsd-screensaver-proxy \
    mate-screensaver > /dev/null 2>&1
xscreensaver &
"$HOME"/bin/xscreensaver-watch &

sleep 25

xset r rate 250 30 # Set again.
EOF

notice `uname -n` fluxbox is starting &
trap 'notice `uname -n` fluxbox is stopping &' 0 INT TERM QUIT EXIT

# Print traps to stdio for X log.
trap

/opt/fluxbox/bin/fluxbox; gnome-session-quit --logout --no-prompt
