#!/usr/bin/env bash
# Install `bb`: A Clojure babushka for the grey areas of Bash.

BB="$REQD_OPT"/babashka/bin/bb
BB_URL=https://github.com/borkdude/babashka/releases


check() {
    reqd_ls "$BB"
    reqd_run_once
}

install() {
    rm -f "$BB"

    qwertyrc > bb.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc bb.qwertyrc
    "$BB" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=1eae3e6d8b899c6d3a82c095490b75bc7becdf4de8c5a6250c0f9060426e90ba \\
  --output="$BB" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.2.3/babashka-0.2.3-linux-static-amd64.zip

# Mac OS X, 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=70298e0f3bb1f67f5e918134465c135d13fca90e2276c0789f29bed8c740ea5e \\
  --output="$BB" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.2.3/babashka-0.2.3-macos-amd64.zip
EOF
}

reqd_main "$@"
