#!/usr/bin/env bash
# Install `bb`: A Clojure babushka for the grey areas of Bash.

BB="$REQD_OPT"/babashka/bin/bb
BB_URL=https://github.com/borkdude/babashka/releases


check() {
    reqd_ls "$BB"
    reqd_run_once
}

install() {
    rm -f "$BB"

    qwertyrc > bb.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc bb.qwertyrc
    "$BB" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=a89af730bc5d65c1e25541942f8961b783e023823582d3c981c878261e91ef96 \\
  --output="$BB" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.2.4/babashka-0.2.4-linux-static-amd64.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=65933e5b598e8b82762f856b8e942ee459db482ad73f704185b2706ccf8b0818 \\
  --output="$BB" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.2.4/babashka-0.2.4-macos-amd64.zip
EOF
}

reqd_main "$@"
