#!/usr/bin/env bash
# Install `bb`: A Clojure babushka for the grey areas of Bash.

BB="$REQD_OPT"/babashka/bin/bb
BB_URL=https://github.com/borkdude/babashka/releases


check() {
    reqd_ls "$BB"
    reqd_run_once
}

install() {
    rm -f "$BB"

    qwertyrc > bb.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc bb.qwertyrc
    "$BB" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=03057fdcf6257e678fcfec4ccf1442aa5dc8f8f7254998b4d363b852aa2c3801 \\
  --output="$BB" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.5.0/babashka-0.5.0-linux-amd64-static.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$BB'" \\
  --sha256=e1904a61187c4707acca5c4db914f358072a8cf829597e85af4d909f8c7cdbec \\
  --output="$BB" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv bb \$DOWNLOAD' \\
  $BB_URL/download/v0.5.0/babashka-0.5.0-macos-amd64.tar.gz
EOF
}

reqd_main "$@"
