#!/usr/bin/env bash
# Install `circleci-cli` executable for a local CircleCI runtime.

CIRCLECI="$REQD_OPT"/circleci/bin/circleci
CIRCLECI_REV=v0.1.15932
CIRCLECI_256=6d6a78720e760c8ad523bdd8574b6ef6373ae7550bebcb3b597be0877ac2cc0e
CIRCLECI_URL=https://github.com/CircleCI-Public/circleci-cli

check() {
    reqd_ls "$CIRCLECI"
    reqd_run_once
}

pretest() {
    reqd_echo 'Checking for `docker` ...'
    which docker
}

install() {
    rm -f "$CIRCLECI"

    qwertyrc > circleci.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc circleci.qwertyrc
    "$CIRCLECI" version
}

qwertyrc() {
    url="$CIRCLECI_URL/releases/download/${CIRCLECI_REV}"

    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when='! test -e $CIRCLECI' \\
  --sha256="$CIRCLECI_256" \\
  --output="$CIRCLECI" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv circleci-cli*/circleci \$DOWNLOAD' \\
  "$url"/circleci-cli_${CIRCLECI_REV##v}_linux_amd64.tar.gz
EOF
}

reqd_main "$@"
