#!/usr/bin/env bash
# Install Clojure.

PREFIX="$REQD_OPT"/clojure
INSTALL_URL=https://download.clojure.org/install/linux-install-1.10.2.774.sh
SHA256=6d39603e84ad2622e5ae601436f02a1ee4a57e4e35dc49098b01a7d142a13d4a

check() {
    reqd_ls "$PREFIX"/bin/clj
    reqd_run_once
}

pretest() {
    java -version
}

install() {
    rm -fr "$PREFIX"
    "$REQD_BIN"/qwerty.sh --sha256=$SHA256 $INSTALL_URL | bash -s - -p $PREFIX

    reqd_echo 'Proving `clj` ...'
    PATH="$PREFIX"/bin:"$PATH" clj -e "(print *clojure-version*)"

    # Bootstrap `lein` & `boot`, already available at $HOME/bin.
    reqd_echo 'Proving `lein` ...'
    PATH="$PREFIX"/bin:"$PATH" lein repl <<< '(print *clojure-version*)'
    reqd_echo 'Proving `boot` ...'
    PATH="$PREFIX"/bin:"$PATH" boot call -e "(print *clojure-version*)"; echo
}

reqd_main "$@"
