#!/usr/bin/env bash
# Install Clojure.

PREFIX="$REQD_OPT"/clojure
INSTALL_URL=https://download.clojure.org/install/linux-install-1.10.3.822.sh
SHA256=ebc820fe0e74de4bd77e6d5bd7db4a262ec1902efdf4d0553309485afcd75abf

check() {
    reqd_ls "$PREFIX"/bin/clj
    reqd_run_once
}

pretest() {
    java -version
}

install() {
    rm -fr "$PREFIX"
    "$REQD_BIN"/qwerty.sh --sha256=$SHA256 $INSTALL_URL | bash -s - -p $PREFIX

    reqd_echo 'Proving `clj` ...'
    PATH="$PREFIX"/bin:"$PATH" clj -e "(print *clojure-version*)"

    # Bootstrap `lein` & `boot`, already available at $HOME/bin.
    reqd_echo 'Proving `lein` ...'
    PATH="$PREFIX"/bin:"$PATH" lein repl <<< '(print *clojure-version*)'
    reqd_echo 'Proving `boot` ...'
    PATH="$PREFIX"/bin:"$PATH" boot call -e "(print *clojure-version*)"; echo
}

reqd_main "$@"
