#!/usr/bin/env bash
# Install packages with Conda if `conda` is installed.

CONDA_PREFIX="$REQD_OPT"/conda
CONDA="$CONDA_PREFIX"/bin/conda

check() {
    if reqd_ls "$CONDA"; then
        reqd_newer_than "$CONDA"
        check_smoke
    fi
    reqd_run_once
}

check_smoke() {
    # Smoke test with e.g.:
    #
    #     reqd_ls "$CONDA_PREFIX"/bin/program

    return
}

install() {
    if ! reqd_ls "$CONDA"; then
        reqd_error "conda not installed. skipping ..."
        return
    fi

    # Add `conda install` lines here.
}

reqd_main "$@"
