#!/usr/bin/env bash
# Install miniconda for minimal Conda installation of Python tools.

PREFIX="$REQD_OPT"/conda
INSTALLER="$PREFIX"/bin/install-miniconda.sh

source "$REQD_LIB"/core.bash

check() {
    reqd_ls "$PREFIX"/bin/conda
    reqd_run_once
}

install() {
    # ARM architecture is unsupported by Conda (as of Sep 2020).
    if startswith "arm" "$(uname -m)"; then
        reqd_error "Skipping installation on ARM architecture ..."
        return
    fi

    if contains " " "$PREFIX"; then
        reqd_error "Conda does not support installation with spaces: $PREFIX"
        return 1
    fi

    rm -fr "$PREFIX"

    qwertyrc > miniconda.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc miniconda.qwertyrc

    # Miniconda installer does not respect its own shebang.
    sh "$INSTALLER" -p "$PREFIX" -b -u

    # Inform .bashrc to avoid adding lib/ to LD_LIBRARY_PATH & PKG_CONFIG_PATH.
    touch "$PREFIX"/.skip-lib

    "$PREFIX"/bin/conda --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --output="$INSTALLER" \\
  --chmod=644 \\
  --sha256=536817d1b14cb1ada88900f5be51ce0a5e042bae178b5550e62f61e223deae7c \\
  https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --output="$INSTALLER" \\
  --chmod=644 \\
  --sha256=b3bf77cbb81ee235ec6858146a2a84d20f8ecdeb614678030c39baacb5acbed1 \\
  https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-MacOSX-x86_64.sh

EOF
}

reqd_main "$@"
