#!/usr/bin/env bash
# Install miniconda for minimal Conda installation of Python tools.

PREFIX="$REQD_OPT"/conda
INSTALLER="$PREFIX"/bin/install-miniconda.sh

source "$REQD_LIB"/core.bash

check() {
    reqd_ls "$PREFIX"/bin/conda
    reqd_run_once
}

install() {
    # ARM architecture is unsupported by Conda (as of Sep 2020).
    if startswith "arm" "$(uname -m)"; then
        reqd_error "Skipping installation on ARM architecture ..."
        return
    fi

    if contains " " "$PREFIX"; then
        reqd_error "Conda does not support installation with spaces: $PREFIX"
        return 1
    fi

    rm -fr "$PREFIX"

    qwertyrc > miniconda.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc miniconda.qwertyrc

    # Miniconda installer does not respect its own shebang.
    sh "$INSTALLER" -p "$PREFIX" -b -u

    # Inform .bashrc to avoid adding lib/ to LD_LIBRARY_PATH & PKG_CONFIG_PATH.
    touch "$PREFIX"/.skip-lib

    "$PREFIX"/bin/conda --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --output="$INSTALLER" \\
  --chmod=644 \\
  --sha256=1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f \\
  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --output="$INSTALLER" \\
  --chmod=644 \\
  --sha256=786de9721f43e2c7d2803144c635f5f6e4823483536dc141ccd82dbb927cd508 \\
  https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

EOF
}

reqd_main "$@"
