#!/usr/bin/env bash
# Install DuckDB.

DUCKDB="$REQD_OPT"/duckdb/bin/duckdb
DUCKDB_URL=https://github.com/duckdb/duckdb/releases

check() {
    reqd_ls "$DUCKDB"
    reqd_run_once
}

install() {
    rm -f "$DUCKDB"

    qwertyrc > duckdb.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc duckdb.qwertyrc
    "$DUCKDB" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$DUCKDB'" \\
  --sha256=9eb2b905b578122c61f09d74874fe1ec1fbfc09a63d74900b6a03364135edd6e \\
  --output="$DUCKDB" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv duckdb \$DOWNLOAD' \\
  $DUCKDB_URL/download/v0.5.0/duckdb_cli-linux-amd64.zip
EOF
}

reqd_main "$@"
