#!/usr/bin/env bash
# Install Go (golang).

PREFIX="$REQD_OPT"/go

PACKAGES=""
PACKAGES="$PACKAGES github.com/mikefarah/yq/v3"
PACKAGES="$PACKAGES mvdan.cc/sh/v3/cmd/shfmt"
PACKAGES="$PACKAGES sigs.k8s.io/kind"

check() {
    reqd_ls "$PREFIX"/bin/go
    reqd_run_once
}

install() {
    rm -fr "$PREFIX"

    qwertyrc > go.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc go.qwertyrc

    cd "$REQD_OPT"
    tar -xvzf "$REQD_RES"/go.tar.gz

    "$PREFIX"/bin/go version

    for package in $PACKAGES; do
        GO111MODULE=on "$PREFIX"/bin/go get "$package"
    done
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --output=go.tar.gz \\
  --sha256=7154e88f5a8047aad4b80ebace58a059e36e7e2e4eb3b383127a28c711b4ff59 \\
  https://golang.org/dl/go1.16.4.linux-amd64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --output=go.tar.gz \\
  --sha256=a53391a800ddec749ee90d38992babb27b95cfb864027350c737b9aa8e069494 \\
  https://golang.org/dl/go1.16.4.linux-armv6l.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=18fe94775763db3878717393b6d41371b0b45206055e49b3838328120c977d13 \\
  --output=go.tar.gz \\
  https://golang.org/dl/go1.16.4.darwin-amd64.tar.gz
EOF
}

reqd_main "$@"
