#!/usr/bin/env bash
# Install Go (golang).

PREFIX="$REQD_OPT"/go

PACKAGES=""
PACKAGES="$PACKAGES github.com/mikefarah/yq/v3@latest"
PACKAGES="$PACKAGES mvdan.cc/sh/v3/cmd/shfmt@latest"
PACKAGES="$PACKAGES sigs.k8s.io/kind@latest"

check() {
    reqd_ls "$PREFIX"/bin/go
    reqd_run_once
}

install() {
    rm -fr "$PREFIX"

    qwertyrc > go.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc go.qwertyrc

    cd "$REQD_OPT"
    tar -xvzf "$REQD_RES"/go.tar.gz

    "$PREFIX"/bin/go version

    for package in $PACKAGES; do
        "$PREFIX"/bin/go install "$package"
    done
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --output=go.tar.gz \\
  --sha256=6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d \\
  https://golang.org/dl/go1.17.linux-amd64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --output=go.tar.gz \\
  --sha256=ae89d33f4e4acc222bdb04331933d5ece4ae71039812f6ccd7493cb3e8ddfb4e \\
  https://golang.org/dl/go1.17.linux-armv6l.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=355bd544ce08d7d484d9d7de05a71b5c6f5bc10aa4b316688c2192aeb3dacfd1 \\
  --output=go.tar.gz \\
  https://golang.org/dl/go1.17.darwin-amd64.tar.gz
EOF
}

reqd_main "$@"
