#!/usr/bin/env bash
# Install `stack` default `ghc` (if `stack` is found).

SYSTEM_STACK=/opt/haskell/bin/stack

check() {
    reqd_ls "$HOME"/.stack
}

install() {
    local stack

    # Find `stack`, preferring SYSTEM_STACK if available.
    stack=$(which stack 2>/dev/null)
    if [ -x "$SYSTEM_STACK" ]; then
        stack="$SYSTEM_STACK"
    fi

    if [ ! -x "$stack" ]; then
        reqd_error 'No `stack` found.'
        return
    fi

    # Download `ghc` automatically.
    "$stack" ghc -- --version
}

reqd_main "$@"
