#!/usr/bin/env bash
# Install `helm` for Kubernetes.

HELM="$REQD_OPT"/kubernetes/bin/helm
HELM_URL=https://get.helm.sh

check() {
    reqd_ls "$HELM"
    reqd_run_once
}

install() {
    rm -f "$HELM"

    qwertyrc > helm.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc helm.qwertyrc
    "$HELM" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=01b317c506f8b6ad60b11b1dc3f093276bb703281cb1ae01132752253ec706a2 \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.2-linux-amd64.tar.gz

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$HELM'" \\
  --sha256=98d090fc1769f5bf7451c15f6ed5a173a1ce5175eca32070ac19064d36470f1b \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-arm/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.2-linux-arm.tar.gz

# Mac OS X, 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=68040e9a2f147a92c2f66ce009069826df11f9d1e1c6b78c7457066080ad3229 \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv darwin-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.2-darwin-amd64.tar.gz
EOF
}

reqd_main "$@"
