#!/usr/bin/env bash
# Install `helm` for Kubernetes.

HELM="$REQD_OPT"/kubernetes/bin/helm
HELM_URL=https://get.helm.sh

check() {
    reqd_ls "$HELM"
    reqd_run_once
}

install() {
    rm -f "$HELM"

    qwertyrc > helm.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc helm.qwertyrc
    "$HELM" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=a8ddb4e30435b5fd45308ecce5eaad676d64a5de9c89660b56face3fe990b318 \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.4-linux-amd64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$HELM'" \\
  --sha256=1a9cc09ef06db29a0232d265f73625056a0cb089e5a16b0a5ef8e810e0533157 \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-arm/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.4-linux-arm.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=072c40c743d30efdb8231ca03bab55caee7935e52175e42271a0c3bc37ec0b7b \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv darwin-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.4-darwin-amd64.tar.gz
EOF
}

reqd_main "$@"
