#!/usr/bin/env bash
# Install `helm` for Kubernetes.

HELM="$REQD_OPT"/kubernetes/bin/helm
HELM_URL=https://get.helm.sh

check() {
    reqd_ls "$HELM"
    reqd_run_once
}

install() {
    rm -f "$HELM"

    qwertyrc > helm.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc helm.qwertyrc
    "$HELM" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=3fff0354d5fba4c73ebd5db59a59db72f8a5bbe1117a0b355b0c2983e98db95b \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.0-linux-amd64.tar.gz

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$HELM'" \\
  --sha256=ca8792da269b72235987ea7245d1450a859b2c0658f591737d74b6c56cd9b1fa \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv linux-arm/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.0-linux-arm.tar.gz

# Mac OS X, 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$HELM'" \\
  --sha256=53378d8de087395ece3876795111a8077f2451f080ec6150d777cc3105214520 \\
  --output="$HELM" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv darwin-amd64/helm \$DOWNLOAD' \\
  $HELM_URL/helm-v3.5.0-darwin-amd64.tar.gz
EOF
}

reqd_main "$@"
