#!/usr/bin/env bash
# Install `k9s` for Kubernetes.

K9S="$REQD_OPT"/kubernetes/bin/k9s
K9S_URL=https://github.com/derailed/k9s/releases

check() {
    reqd_ls "$K9S"
    reqd_run_once
}

install() {
    rm -f "$K9S"

    qwertyrc > k9s.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc k9s.qwertyrc
    "$K9S" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=bf1fbcf145b8e021b675bae009183e7028afbce52fc44c37f6a0dd2982152c21 \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.10/k9s_v0.24.10_Linux_x86_64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$K9S'" \\
  --sha256=589e03334de58c6bb4062818bb9801a7565864a2207376580d3630e61128e569 \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.10/k9s_v0.24.10_Linux_arm.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=742fdc53d7e2f3b9bbd78de45b7dc9e453f84f5d3f6e594c057d4d823d8dda42 \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.10/k9s_v0.24.10_Darwin_x86_64.tar.gz
EOF
}

reqd_main "$@"
