#!/usr/bin/env bash
# Install `k9s` for Kubernetes.

K9S="$REQD_OPT"/kubernetes/bin/k9s
K9S_URL=https://github.com/derailed/k9s/releases

check() {
    reqd_ls "$K9S"
    reqd_run_once
}

install() {
    rm -f "$K9S"

    qwertyrc > k9s.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc k9s.qwertyrc
    "$K9S" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=0590c32c20cd22416f2a06fad9155257c156e32c60e8757bf96d5a28cb1720dd \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.15/k9s_Linux_x86_64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$K9S'" \\
  --sha256=95be61742f6e7ed6c0f98c493113b87db7faff9cc5cf85246c9b51522bca8d7c \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.15/k9s_Linux_arm.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=ba33b0e0fd0679668b7af85fe95fbdc78cfc4ad4e10512146656ee382f1ce8ae \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.15/k9s_Darwin_x86_64.tar.gz
EOF
}

reqd_main "$@"
