#!/usr/bin/env bash
# Install `k9s` for Kubernetes.

K9S="$REQD_OPT"/kubernetes/bin/k9s
K9S_URL=https://github.com/derailed/k9s/releases

check() {
    reqd_ls "$K9S"
    reqd_run_once
}

install() {
    rm -f "$K9S"

    qwertyrc > k9s.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc k9s.qwertyrc
    "$K9S" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=5096820f8c55708b059c3a01c5baeecca210c6b955740419d6b30b3132589619 \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.7/k9s_Linux_x86_64.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$K9S'" \\
  --sha256=db14018adc67332827b17265cad1844f4f3021fe8e8abbf201d1fb198a058b9b \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.7/k9s_Linux_arm.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$K9S'" \\
  --sha256=6a18446b0e134763c73c40808a06b1fe5ad93a8cfa3d999f57f5e4e573c56ef7 \\
  --output="$K9S" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv k9s \$DOWNLOAD' \\
  $K9S_URL/download/v0.24.7/k9s_Darwin_x86_64.tar.gz
EOF
}

reqd_main "$@"
