#!/usr/bin/env bash
# Install Kotlin standalone compiler.

KOTLIN_URL=https://github.com/JetBrains/kotlin

KOTLIN_V=1.5.10
KOTLIN_SHA256=2f8de1d73b816354055ff6a4b974b711c11ad55a68b948ed30b38155706b3c4e

check() {
    reqd_ls "$REQD_OPT"/kotlinc/bin/kotlinc
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/kotlinc

    eval "$QWERTY_SH" \
      --output=kotlin.zip \
      --sha256="$KOTLIN_SHA256" \
      "$KOTLIN_URL"/releases/download/v$KOTLIN_V/kotlin-compiler-$KOTLIN_V.zip

    cd "$REQD_OPT"
    unzip -o "$REQD_RES"/kotlin.zip

    "$REQD_OPT"/kotlinc/bin/kotlinc -version
}

reqd_main "$@"
