#!/usr/bin/env bash
# Install Kotlin standalone compiler.

KOTLIN_URL=https://github.com/JetBrains/kotlin

KOTLIN_V=1.3.71
KOTLIN_SHA256=7adb77dad99c6d2f7bde9f8bafe4c6244a04587a8e36e62b074d00eda9f8e74a

check() {
    reqd_ls "$REQD_OPT"/kotlinc/bin/kotlinc
    reqd_run_once
}

install() {
    eval "$QWERTY_SH" \
      --output=kotlin.zip \
      --sha256="$KOTLIN_SHA256" \
      "$KOTLIN_URL"/releases/download/v$KOTLIN_V/kotlin-compiler-$KOTLIN_V.zip

    cd "$REQD_OPT"
    unzip -o "$REQD_RES"/kotlin.zip

    "$REQD_OPT"/kotlinc/bin/kotlinc -version
}

reqd_main "$@"
