#!/usr/bin/env bash
# Install Kotlin standalone compiler.

KOTLIN_URL=https://github.com/JetBrains/kotlin

KOTLIN_V=1.4.10
KOTLIN_SHA256=bb1a21d70e521a01ae104e99a082a6e7bb58699b86347049da521d175d0dace7

check() {
    reqd_ls "$REQD_OPT"/kotlinc/bin/kotlinc
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/kotlinc

    eval "$QWERTY_SH" \
      --output=kotlin.zip \
      --sha256="$KOTLIN_SHA256" \
      "$KOTLIN_URL"/releases/download/v$KOTLIN_V/kotlin-compiler-$KOTLIN_V.zip

    cd "$REQD_OPT"
    unzip -o "$REQD_RES"/kotlin.zip

    "$REQD_OPT"/kotlinc/bin/kotlinc -version
}

reqd_main "$@"
