#!/usr/bin/env bash
# Install `kubectl` for Kubernetes.

KUBECTL="$REQD_OPT"/kubernetes/bin/kubectl
KUBECTL_URL=https://storage.googleapis.com/kubernetes-release/release

check() {
    reqd_ls "$KUBECTL"
    reqd_run_once
}

install() {
    rm -f "$KUBECTL"

    qwertyrc > kubectl.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc kubectl.qwertyrc
    "$KUBECTL" help
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --sha256=58785190e2b4fc6891e01108e41f9ba5db26e04cebb7c1ac639919a931ce9233 \\
  --output="$KUBECTL" --chmod=755 \\
  $KUBECTL_URL/v1.21.1/bin/linux/amd64/kubectl

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=4a81a072bbb55dc5ef1e90609f7d38a67ede5946593653dee0be94f3850296a9 \\
  --output="$KUBECTL" --chmod=755 \\
  $KUBECTL_URL/v1.21.1/bin/darwin/amd64/kubectl
EOF
}

reqd_main "$@"
