#!/usr/bin/env bash
# Configure Node.js.

NPM_PACKAGES="http-server @zwave-js/zwlf-parser"

check() {
    reqd_run_once
}

pretest() {
    reqd_echo 'Checking for `node` ...'

    which node > /dev/null 2>&1
    which npm > /dev/null 2>&1

    reqd_echo "node $(node --version)"
    reqd_echo "npm v$(npm --version)"
}

install() {
    npm config set prefix '~/.npm-global'

    npm install -g npm yarn
    npm install -g bs-platform # Reason / ReasonML (OCaml)
    npm install -g nbb # Node.js variant of `bb` for Clojure scripting.

    rehash >/dev/null 2>&1 || true

    which npm
    which yarn
    which bsc
    which nbb

    reqd_echo "npm v$(npm --version)"
    reqd_echo "yarn v$(yarn --version)"
    reqd_echo "$(bsc -version)"
    reqd_echo "$(nbb -e '(print "nbb answer:" (* 6 7))')"

    reqd_echo "Installing $NPM_PACKAGES ..."
    npm install -g "$NPM_PACKAGES"
}

reqd_main "$@"
