#!/usr/bin/env bash
# Configure Node.js.

check() {
    reqd_run_once
}

pretest() {
    reqd_echo 'Checking for `node` ...'

    which node > /dev/null 2>&1
    which npm > /dev/null 2>&1

    reqd_echo "node $(node --version)"
    reqd_echo "npm v$(npm --version)"
}

install() {
    npm config set prefix '~/.npm-global'

    npm install -g npm yarn
    npm install -g bs-platform # Reason / ReasonML (OCaml)

    which npm
    which yarn
    which bsc

    reqd_echo "npm v$(npm --version)"
    reqd_echo "yarn v$(yarn --version)"
    reqd_echo "$(bsc -version)"
}

reqd_main "$@"
