#!/usr/bin/env bash
# Install `opam` for OCaml development.

OPAM="$REQD_OPT"/ocaml/bin/opam
OPAM_URL=https://github.com/ocaml/opam

check() {
    reqd_ls "$OPAM"
    reqd_run_once
}

install() {
    rm -f "$OPAM"

    qwertyrc > opam.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc opam.qwertyrc
    "$OPAM" --version

    "$OPAM" init --yes --auto-setup --disable-shell-hook --reinit

    # $HOME git (.homegit) tracks opam setup files.
    # When user-setup is needed, use the following.
    #
    # "$OPAM" --yes user-setup install
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --sha256=c9148c4670507f8f12df64307f9457b300283bc7709389b9659fd58f4c98596e \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.1.2/opam-2.1.2-x86_64-linux

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --sha256=f992facb03556273b83bbb3255d82f68f3e0a607539f044ba93555c7000807e4 \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.1.2/opam-2.1.2-armhf-linux

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=735d13e28720db2821e06ef4c4648fab10984e20576e9bd32270db12a456a424 \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.1.2/opam-2.1.2-x86_64-macos
EOF
}

reqd_main "$@"
