#!/usr/bin/env bash
# Install `opam` for OCaml development.

OPAM="$REQD_OPT"/ocaml/bin/opam
OPAM_URL=https://github.com/ocaml/opam

check() {
    reqd_ls "$OPAM"
    reqd_run_once
}

install() {
    rm -f "$OPAM"

    qwertyrc > opam.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc opam.qwertyrc
    "$OPAM" --version

    "$OPAM" init --auto-setup --disable-shell-hook --reinit

    # $HOME git (.homegit) tracks opam setup files.
    # When user-setup is needed, use the following.
    #
    # "$OPAM" --yes user-setup install
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --sha256=d9cf2652212f78087f2eaf9647cefad601f2f1594cf0074c0579d5d21675e49b \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.0.7/opam-2.0.7-x86_64-linux

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --sha256=7646b0c7b8c1d2b4b483104bd5711509e2382e1b0ec74cda3bbb9bf930a5370d \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.0.7/opam-2.0.7-armhf-linux

# macOS 64-bit
  --sys=darwin --arch=x86_64 \\
  --sha256=d559a2d9b6e8cb3b19fbbee8e236113d60999f2db93e59d7f944f7c52af2174e \\
  --output="$OPAM" --chmod=755 \\
  $OPAM_URL/releases/download/2.0.7/opam-2.0.7-x86_64-darwin
EOF
}

reqd_main "$@"
