#!/usr/bin/env bash
# Install Packer.

PACKER="$REQD_OPT"/packer/bin/packer
PACKER_URL=https://releases.hashicorp.com/packer

check() {
    reqd_ls "$PACKER"
    reqd_run_once
}

install() {
    rm -f "$PACKER"

    qwertyrc > packer.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc packer.qwertyrc
    "$PACKER" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$PACKER'" \\
  --sha256=9429c3a6f80b406dbddb9b30a4e468aeac59ab6ae4d09618c8d70c4f4188442e \\
  --output="$PACKER" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv packer \$DOWNLOAD' \\
  $PACKER_URL/1.7.2/packer_1.7.2_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$PACKER'" \\
  --sha256=bf500157f7f7af06cdf986f1f9e272032d26d06ffd0c79d0b924c1641a05e5ae \\
  --output="$PACKER" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv packer \$DOWNLOAD' \\
  $PACKER_URL/1.7.2/packer_1.7.2_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$PACKER'" \\
  --sha256=2dd688672157eed5d9f5126b1dd160862926ab698dc91e4ffb5a7fc2deb0b037 \\
  --output="$PACKER" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv packer \$DOWNLOAD' \\
  $PACKER_URL/1.7.2/packer_1.7.2_darwin_amd64.zip
EOF
}

reqd_main "$@"
