#!/usr/bin/env bash
# Install `pack` for Cloud Native Buildpacks.
#
# https://buildpacks.io/

PACK="$REQD_OPT"/pack/bin/pack
PACK_URL=https://github.com/buildpacks/pack/releases

check() {
    reqd_ls "$PACK"
    reqd_run_once
}

install() {
    rm -f "$PACK"

    qwertyrc > pack.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc pack.qwertyrc
    "$PACK" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$PACK'" \\
  --sha256=016155c90549b6154699fff5433b7e6d559b9aba9ac7cbf7d7b58ccd953921ca \\
  --output="$PACK" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv pack \$DOWNLOAD' \\
  $PACK_URL/download/v0.19.0/pack-v0.19.0-linux.tgz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$PACK'" \\
  --sha256=5554179d3d88fdac1b4f56fdc7b765037d66556f1dc493147e1cbbea83783669 \\
  --output="$PACK" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv pack \$DOWNLOAD' \\
  $PACK_URL/download/v0.19.0/pack-v0.19.0-macos.tgz
EOF
}

reqd_main "$@"
