#!/usr/bin/env bash
# Install Pulumi.

PULUMI="$REQD_OPT"/pulumi/bin/pulumi
PULUMI_URL=https://github.com/pulumi/pulumi

check() {
    reqd_ls "$PULUMI"
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/pulumi

    qwertyrc > pulumi.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc pulumi.qwertyrc

    cd "$REQD_OPT"
    mkdir -p pulumi
    cd pulumi
    tar -xvzf "$REQD_RES"/pulumi.tar.gz
    mv pulumi bin

    "$PULUMI" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --sha256=6a30d95eb31e9c7e2b8904fa00977f5a0f1b43fd55da80b7d4753cd1d0414f86 \\
  --output=pulumi.tar.gz \\
  $PULUMI_URL/releases/download/v3.7.0/pulumi-v3.7.0-linux-x64.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=ef6bbee97f4b9ae811f8f17bccd8fae9c347efb98cf1d98790955e2e925cb1d1 \\
  --output=pulumi.tar.gz \\
  $PULUMI_URL/releases/download/v3.7.0/pulumi-v3.7.0-darwin-x64.tar.gz
EOF
}

reqd_main "$@"
