#!/usr/bin/env bash
# Install Pulumi.

PULUMI_URL=https://get.pulumi.com/releases/sdk/pulumi-v2.12.0-linux-x64.tar.gz
PULUMI_SHA256=0ac0e4dff4a3d0cbca1db077c70b01ee8aa0b15e22a1e2b44efd6a1e296ae39e

check() {
    reqd_ls "$REQD_OPT"/pulumi/bin/pulumi
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/pulumi

    eval "$QWERTY_SH" \
         --sys=linux --arch=x86_64 \
         --output=pulumi.tar.gz --sha256="$PULUMI_SHA256" "$PULUMI_URL"

    cd "$REQD_OPT"
    mkdir -p pulumi
    cd pulumi
    tar -xvzf "$REQD_RES"/pulumi.tar.gz
    mv pulumi bin

    "$REQD_OPT"/pulumi/bin/pulumi version
}

reqd_main "$@"
