#!/usr/bin/env bash
# Install pyenv for Python.
#
# Note: Cleaning up old versions installed by pyenv is left as a manual task.

PYENV_ROOT="$HOME/.pyenv"
PYENV_URL=https://github.com/pyenv/pyenv.git

PACKAGES2="pyflakes"
PACKAGES3="pyflakes youtube-dl"

check() {
    reqd_run_once
}

install() {
    if [ ! -e "$PYENV_ROOT" ]; then
        git clone "$PYENV_URL" "$PYENV_ROOT"
    else
        cd "$PYENV_ROOT"; git pull
    fi

    export PATH="$PYENV_ROOT"/bin:"$PYENV_ROOT"/shims:"$PATH"

    pyenv install --skip-existing 2.7.18
    pyenv install --skip-existing 3.8.2

    pyenv global 3.8.2 2.7.18

    pip2 install --upgrade pip setuptools wheel
    pip3 install --upgrade pip setuptools wheel

    pip2 install $PACKAGES2
    pip3 install $PACKAGES3
}

reqd_main "$@"
