#!/usr/bin/env bash
# Install pyenv for Python.
#
# Note: Cleaning up old versions installed by pyenv is left as a manual task.

PYENV_ROOT="$HOME/.pyenv"
PYENV_URL=https://github.com/pyenv/pyenv.git

PYENV_VIRTUALENV_ROOT="$PYENV_ROOT"/plugins/pyenv-virtualenv
PYENV_VIRTUALENV_URL=https://github.com/pyenv/pyenv-virtualenv.git

PACKAGES2="pyflakes"

PACKAGES3="pdm pipenv poetry"
PACKAGES3="$PACKAGES3 python-language-server"
PACKAGES3="$PACKAGES3 black flake8 isort pre-commit pyflakes"
PACKAGES3="$PACKAGES3 nltk syllables"
PACKAGES3="$PACKAGES3 httpie"
PACKAGES3="$PACKAGES3 youtube-dl"

check() {
    reqd_run_once
}

install() {
    if [ ! -e "$PYENV_ROOT" ]; then
        git clone "$PYENV_URL" "$PYENV_ROOT"
    else
        cd "$PYENV_ROOT"; git pull
    fi

    if [ ! -e "$PYENV_VIRTUALENV_ROOT" ]; then
        git clone "$PYENV_VIRTUALENV_URL" "$PYENV_VIRTUALENV_ROOT"
    else
        cd "$PYENV_VIRTUALENV_ROOT"; git pull
    fi

    export PATH="$PYENV_ROOT"/bin:"$PYENV_ROOT"/shims:"$PATH"

    pyenv install --skip-existing 2.7.18
    pyenv install --skip-existing 3.9.6
    pyenv install --skip-existing 3.10-dev

    pyenv global 3.9.6 2.7.18 3.10-dev

    python2.7  -m pip install --upgrade pip setuptools wheel
    python3.9  -m pip install --upgrade pip setuptools wheel
    python3.10 -m pip install --upgrade pip setuptools wheel

    python2.7  -m pip install ${PYTHON2_PACKAGES:-$PACKAGES2}
    python3.9  -m pip install ${PYTHON3_PACKAGES:-$PACKAGES3}
    python3.10 -m pip install ${PYTHON3_PACKAGES:-$PACKAGES3}
}

reqd_main "$@"
