#!/usr/bin/env bash
# Install Rancher Kubernetes Engine (RKE) `rke`.

RKE="$REQD_OPT"/kubernetes/bin/rke
RKE_URL=https://github.com/rancher/rke/releases

check() {
    reqd_ls "$RKE"
    reqd_run_once
}

install() {
    rm -f "$RKE"

    qwertyrc > rke.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc rke.qwertyrc
    "$RKE" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --sha256=77d2dc6af0d9388cba7dddea9ce3339d8e99618a32da68d043018ef63840bc6f \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL//download/v1.2.5/rke_linux-amd64

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --sha256=0acc3b797b5adb44ccf3474755db510dafb73c6678ef403955f1bb9fa2ee3899 \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL//download/v1.2.5/rke_linux-arm

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --sha256=773c08845f2c094e1116e7aa321e0113658b97335488ac83490406cf43062901 \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL/download/v1.2.5/rke_darwin-amd64
EOF
}

reqd_main "$@"
