#!/usr/bin/env bash
# Install Rancher Kubernetes Engine (RKE) `rke`.

RKE="$REQD_OPT"/kubernetes/bin/rke
RKE_URL=https://github.com/rancher/rke/releases

check() {
    reqd_ls "$RKE"
    reqd_run_once
}

install() {
    rm -f "$RKE"

    qwertyrc > rke.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc rke.qwertyrc
    "$RKE" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --sha256=61bb428b4d3111bdbfe58fada000328884262bdfa92cd6dbb620560a903e9c66 \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL//download/v1.2.3/rke_linux-amd64

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --sha256=2e4efa687ae4362c6564026e602caea8df53ff92514edfe23e783e9b0c99bcec \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL//download/v1.2.3/rke_linux-arm

# macOS 64-bit
  --sys=darwin --arch=x86_64 \\
  --sha256=eb07c7775ce47ba199ec266b6a0aaa3a24d32d6370e799386981a9dceb6f2836 \\
  --output="$RKE" --chmod=755 \\
  $RKE_URL/download/v1.2.3/rke_darwin-amd64
EOF
}

reqd_main "$@"
