#!/usr/bin/env bash
# Install `sbt` for Scala.

SBT_URL=https://piccolo.link/sbt-1.3.13.tgz
SBT_SHA256=854154de27a7d8c13b5a0f9a297cd1f254cc13b44588dae507e5d4fb2741bd22

check() {
    reqd_ls "$REQD_OPT"/sbt/bin/sbt
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/sbt

    eval "$QWERTY_SH" --output=sbt.tar.gz --sha256="$SBT_SHA256" "$SBT_URL"

    cd "$REQD_OPT"
    tar -xvzf "$REQD_RES"/sbt.tar.gz

    "$REQD_OPT"/sbt/bin/sbt --version
}

reqd_main "$@"
