#!/usr/bin/env bash
# Install `sbt` for Scala.

SBT_URL=https://github.com/sbt/sbt/releases/download/v1.5.4/sbt-1.5.4.tgz
SBT_SHA256=8e173aba17690be9b60f941990bb54b6755eb09e8b1cf445a03da6fe19a1b20c

check() {
    reqd_ls "$REQD_OPT"/sbt/bin/sbt
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/sbt

    eval "$QWERTY_SH" --output=sbt.tar.gz --sha256="$SBT_SHA256" "$SBT_URL"

    cd "$REQD_OPT"
    tar -xvzf "$REQD_RES"/sbt.tar.gz

    "$REQD_OPT"/sbt/bin/sbt --version
}

reqd_main "$@"
