#!/usr/bin/env bash
# Install `sbt` for Scala.

SBT_URL=https://github.com/sbt/sbt/releases/download/v1.5.0/sbt-1.5.0.tgz
SBT_SHA256=aadf110a48ea77c02ce63a9cc033d9fcd02b634e89e8f22dfe13ed21592042b6

check() {
    reqd_ls "$REQD_OPT"/sbt/bin/sbt
    reqd_run_once
}

install() {
    rm -fr "$REQD_OPT"/sbt

    eval "$QWERTY_SH" --output=sbt.tar.gz --sha256="$SBT_SHA256" "$SBT_URL"

    cd "$REQD_OPT"
    tar -xvzf "$REQD_RES"/sbt.tar.gz

    "$REQD_OPT"/sbt/bin/sbt --version
}

reqd_main "$@"
