#!/usr/bin/env bash
# Sync ~/src/ files with ~/src/.overlay/, assumed to be network mount/symlink.

# Set defaults.
: "${HOME_SRC:=$HOME/src}"
: "${HOME_SRC_OVERLAY:=$HOME/src/.overlay}"

check() {
    if [ -e "$HOME_SRC_OVERLAY" ]; then
        # Resolves to a path (i.e. symlink/mountpoint exists).
        return 1
    fi
}

install() {
    local path

    # Assume host 'redeye' is primary development machine.
    if [ "$(uname -n)" = "redeye" ]; then
        rsync -av --prune-empty-dirs \
              --include-from="$REQD_ETC"/src-overlay.rsync \
              "$HOME_SRC"/ "$HOME_SRC_OVERLAY"
    fi
}

reqd_main "$@"
