#!/usr/bin/env bash
# Install `tsh` for Teleport (formerly Gravitational).

PREFIX="$REQD_OPT"/teleport
TELEPORT_TSH="$PREFIX"/bin/tsh
TELEPORT_URL=https://get.gravitational.com

check() {
    reqd_ls "$TELEPORT_TSH"
    reqd_run_once
}

install() {
    rm -fr "$PREFIX"

    qwertyrc > teleport.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc teleport.qwertyrc
    "$TELEPORT_TSH" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=4407060fe157014a4b244655029e3c67867988f8b8e4177bc991c7e434212de1 \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v5.1.2-linux-amd64-bin.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=03e54bb0faa933934491292e4cdc4c60e689a126c2748f22b2c6e435c9ba54d3 \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v5.1.2-linux-arm-bin.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=fd4769fea993ab032f09cedbce2cbfd1ed43ebeb0eb2befaac293f0130dc925a \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v5.1.2-darwin-amd64-bin.tar.gz
EOF
}

reqd_main "$@"
