#!/usr/bin/env bash
# Install `tsh` for Teleport (formerly Gravitational).

PREFIX="$REQD_OPT"/teleport
TELEPORT_TSH="$PREFIX"/bin/tsh
TELEPORT_URL=https://get.gravitational.com

check() {
    reqd_ls "$TELEPORT_TSH"
    reqd_run_once
}

install() {
    rm -fr "$PREFIX"

    qwertyrc > teleport.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc teleport.qwertyrc
    "$TELEPORT_TSH" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=5b6c64d7a74b965067b442f8f60013fc4062d5e1c4f74392b1eb3e572cc2a378 \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v6.1.3-linux-amd64-bin.tar.gz

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=12fd2cfdaf1f0739e018eca6848a26ac4da50b43273c9575f441197c50b4739a \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v6.1.3-linux-arm-bin.tar.gz

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TELEPORT_TSH'" \\
  --sha256=be1cc224eca1cf21cec033867b5bdbe8cbd92b1debe992462a65fdfb39d9e3c1 \\
  --output="$TELEPORT_TSH" --chmod=755 \\
  --on-download='tar -xf \$DOWNLOAD && mv teleport/tsh \$DOWNLOAD' \\
  $TELEPORT_URL/teleport-v6.1.3-darwin-amd64-bin.tar.gz
EOF
}

reqd_main "$@"
