#!/usr/bin/env bash
# Install Terraform.

TERRAFORM="$REQD_OPT"/terraform/bin/terraform
TERRAFORM_URL=https://releases.hashicorp.com/terraform

check() {
    reqd_ls "$TERRAFORM"
    reqd_run_once
}

install() {
    rm -f "$TERRAFORM"

    qwertyrc > terraform.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc terraform.qwertyrc
    "$TERRAFORM" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=bc79e47649e2529049a356f9e60e06b47462bf6743534a10a4c16594f443be7b \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.7/terraform_1.0.7_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=be8d9de8c34e3e843ff8cbc713b41ce0c2bd97b0020c80e934443976b4429ae2 \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.7/terraform_1.0.7_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=80ae021d6143c7f7cbf4571f65595d154561a2a25fd934b7a8ccc1ebf3014b9b \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.7/terraform_1.0.7_darwin_amd64.zip
EOF
}

reqd_main "$@"
