#!/usr/bin/env bash
# Install Terraform.

TERRAFORM="$REQD_OPT"/terraform/bin/terraform
TERRAFORM_URL=https://releases.hashicorp.com/terraform

check() {
    reqd_ls "$TERRAFORM"
    reqd_run_once
}

install() {
    rm -f "$TERRAFORM"

    qwertyrc > terraform.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc terraform.qwertyrc
    "$TERRAFORM" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=3b144499e08c245a8039027eb2b84c0495e119f57d79e8fb605864bb48897a7d \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/0.15.5/terraform_0.15.5_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=3122e7ac6353d488d766ac84379139e3d14f564fbe61f4b069f7584ca9c29e01 \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/0.15.5/terraform_0.15.5_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=27d5ae2431240dff928e6483170b570782a8dd1a2b7c32ce1793097af1acb9bd \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/0.15.5/terraform_0.15.5_darwin_amd64.zip
EOF
}

reqd_main "$@"
