#!/usr/bin/env bash
# Install Terraform.

TERRAFORM="$REQD_OPT"/terraform/bin/terraform
TERRAFORM_URL=https://releases.hashicorp.com/terraform

check() {
    reqd_ls "$TERRAFORM"
    reqd_run_once
}

install() {
    rm -f "$TERRAFORM"

    qwertyrc > terraform.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc terraform.qwertyrc
    "$TERRAFORM" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=7ce24478859ab7ca0ba4d8c9c12bb345f52e8efdc42fa3ef9dd30033dbf4b561 \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.5/terraform_1.0.5_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=e34b5274e2fb76d7e6779697304c8f843ee52b523cf212d0bc868c6f4c533ad5 \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.5/terraform_1.0.5_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TERRAFORM'" \\
  --sha256=ae0b07ba099d3d9241e5e8bcdfc88ada8fcbbe302cb1d8f822da866a25e55330 \\
  --output="$TERRAFORM" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv terraform \$DOWNLOAD' \\
  $TERRAFORM_URL/1.0.5/terraform_1.0.5_darwin_amd64.zip
EOF
}

reqd_main "$@"
