#!/usr/bin/env bash
# Install TFLint Terraform linter.

TFLINT="$REQD_OPT"/terraform/bin/tflint
TFLINT_URL=https://github.com/terraform-linters/tflint/releases


check() {
    reqd_ls "$TFLINT"
    reqd_run_once
}

install() {
    rm -f "$TFLINT"

    qwertyrc > tflint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc tflint.qwertyrc
    "$TFLINT" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=cbc01d58a9c4471b9c0b39507a298bdb0fa06d6c48facb578dc8eddf022dbbd2 \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.19.1/tflint_linux_amd64.zip

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TFLINT'" \\
  --sha256=94468d4a46b620e1f9a9eddca343c5086da6dcbc7fb140a49000b8072477262f \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.19.1/tflint_linux_arm.zip

# Mac OS X, 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=085b1ea23696396f8832a6fd7bd2a41ba5d1cf87e000c14922047a998370f3d9 \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.19.1/tflint_darwin_amd64.zip
EOF
}

reqd_main "$@"
