#!/usr/bin/env bash
# Install TFLint Terraform linter.

TFLINT="$REQD_OPT"/terraform/bin/tflint
TFLINT_URL=https://github.com/terraform-linters/tflint/releases


check() {
    reqd_ls "$TFLINT"
    reqd_run_once
}

install() {
    rm -f "$TFLINT"

    qwertyrc > tflint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc tflint.qwertyrc
    "$TFLINT" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=161a32da55672df11ac8eee94ef5eaecd9909ed817ee894f15f5aad4184c454a \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.32.1/tflint_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TFLINT'" \\
  --sha256=589fd924a5d16108e367a52a4f098f7a51868eb00f77c72cdfccf9b4702fbbec \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.32.1/tflint_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=078d00f0efcac6c2827cc80ce5952ed0dc01d830c175181daa03144937d60efc \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.32.1/tflint_darwin_amd64.zip
EOF
}

reqd_main "$@"
