#!/usr/bin/env bash
# Install TFLint Terraform linter.

TFLINT="$REQD_OPT"/terraform/bin/tflint
TFLINT_URL=https://github.com/terraform-linters/tflint/releases


check() {
    reqd_ls "$TFLINT"
    reqd_run_once
}

install() {
    rm -f "$TFLINT"

    qwertyrc > tflint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc tflint.qwertyrc
    "$TFLINT" --version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=9d0c2a6da320e55018c1ae3df9d5f4e4fe0f34274a609b29f306f407db9e6a2e \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.20.2/tflint_linux_amd64.zip

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$TFLINT'" \\
  --sha256=7382042c018ea1b0732ede3dcd0b6556ddbbb8453bfd4a657e69564d7d8045b3 \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.20.2/tflint_linux_arm.zip

# macOS 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$TFLINT'" \\
  --sha256=96f0b689746603d4acb071610425dc6be26b2e0db65eb4023e4f8475fe79775c \\
  --output="$TFLINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv tflint \$DOWNLOAD' \\
  $TFLINT_URL/download/v0.20.2/tflint_darwin_amd64.zip
EOF
}

reqd_main "$@"
