#!/usr/bin/env bash
# Install `tig` text-mode ncurses interface to git.

TIG_PREFIX="$REQD_OPT"/tig
TIG="$TIG_PREFIX"/bin/tig

TIG_URL=https://github.com/jonas/tig/releases

TIG_SHA256=e528068499d558beb99a0a8bca30f59171e71f046d76ee5d945d35027d3925dc
TIG_V=2.5.3

check() {
    reqd_ls "$TIG"
    reqd_run_once
}

resources() {
    local url=$TIG_URL/download/tig-$TIG_V/tig-$TIG_V.tar.gz
    echo $url tig-$TIG_V.tar.gz sha256 $TIG_SHA256
}

install() {
    tar -xzf tig-$TIG_V.tar.gz
    cd tig-$TIG_V

    ./configure --prefix="$TIG_PREFIX"
    make
    make install

    "$TIG" --version
}

reqd_main "$@"
