#!/usr/bin/env bash
# Configure Vagrant.

check() {
    reqd_run_once
}

pretest() {
    reqd_echo 'Checking for `vagrant` ...'

    which vagrant > /dev/null 2>&1
    vagrant --version
}

install() {
    vagrant plugin install vagrant-disksize
    vagrant plugin install vagrant-vbguest
}

reqd_main "$@"
