#!/usr/bin/env bash
# Install Waypoint.

WAYPOINT="$REQD_OPT"/waypoint/bin/waypoint
WAYPOINT_URL=https://releases.hashicorp.com/waypoint

check() {
    reqd_ls "$WAYPOINT"
    reqd_run_once
}

install() {
    rm -f "$WAYPOINT"

    qwertyrc > waypoint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc waypoint.qwertyrc
    "$WAYPOINT" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=79a871123becb2efa133315ce47f540c761996e3796830c55d42e5832367ca59 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.1.4/waypoint_0.1.4_linux_amd64.zip

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=97a6633326cad8de41438f44088f3a9764e9e120594a3043e552e4f4e2714ed9 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.1.4/waypoint_0.1.4_linux_arm.zip

# Mac OS X, 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=888c6db6dd53090b1840f443c017336cae6bb9ae0e5786eea1aba563701f8a75 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.1.4/waypoint_0.1.4_darwin_amd64.zip
EOF
}

reqd_main "$@"
