#!/usr/bin/env bash
# Install Waypoint.

WAYPOINT="$REQD_OPT"/waypoint/bin/waypoint
WAYPOINT_URL=https://releases.hashicorp.com/waypoint

check() {
    reqd_ls "$WAYPOINT"
    reqd_run_once
}

install() {
    rm -f "$WAYPOINT"

    qwertyrc > waypoint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc waypoint.qwertyrc
    "$WAYPOINT" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux x86_64
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=6414d51bf525d4f841a0aa895f322f3ef940e874e038538023c4fabb8173ce15 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.4.0/waypoint_0.4.0_linux_amd64.zip

# GNU/Linux ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=b53091ad803b5361234f880ccdb4f263c08c2b1d89cadd9124c1baa8869082ed \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.4.0/waypoint_0.4.0_linux_arm.zip

# macOS x86_64
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=e4eb68a77fb097fb16dd0a191048a5c77a1b51a9ca5235b5dd1199512d53583b \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.4.0/waypoint_0.4.0_darwin_amd64.zip
EOF
}

reqd_main "$@"
