#!/usr/bin/env bash
# Install Waypoint.

WAYPOINT="$REQD_OPT"/waypoint/bin/waypoint
WAYPOINT_URL=https://releases.hashicorp.com/waypoint

check() {
    reqd_ls "$WAYPOINT"
    reqd_run_once
}

install() {
    rm -f "$WAYPOINT"

    qwertyrc > waypoint.qwertyrc
    "$REQD_BIN"/qwerty.sh --rc waypoint.qwertyrc
    "$WAYPOINT" version
}

qwertyrc() {
    cat - <<EOF
# GNU/Linux 64-bit
  --sys=linux --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=ec93061dd892dc42a233ba31933af6c4ea9b2cb3bc0501c1097a96cee38ae058 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.2.0/waypoint_0.2.0_linux_amd64.zip

# GNU/Linux on ARM
  --sys=linux --arch=arm --all-sub-arch \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=f18ffde32c4308c6a3fb1d93d69ccf899c8a42aa0ad76ec4d96f827e431ee54e \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.2.0/waypoint_0.2.0_linux_arm.zip

# macOS 64-bit
  --sys=darwin --arch=x86_64 \\
  --when="! test -e '$WAYPOINT'" \\
  --sha256=f3db0bd82dee06a35cacd0318181bea002ec4abe6925b72d975ab3e999f63063 \\
  --output="$WAYPOINT" --chmod=755 \\
  --on-download='unzip \$DOWNLOAD && mv waypoint \$DOWNLOAD' \\
  $WAYPOINT_URL/0.2.0/waypoint_0.2.0_darwin_amd64.zip
EOF
}

reqd_main "$@"
