# bashrc - GNU bash source script for bash rc, login
#
# To use:
#     place this directory at ~/.bash.d
#     link to ~/.bashrc, in $HOME directory:
#     ln -s .bash.d/bashrc .bashrc

## Essential shell environment bootstrapping.

# Use custom bash functions.
export BASH_DIR=$HOME/.bash.d
source $BASH_DIR/functions.bash

# virtualenvwrapper for Python
ship WORKON_HOME=$HOME/.virtualenvs
ship WORKON_HOME=$HOME/.virtualenvs-`uname -n`
receive $HOME/bin/virtualenvwrapper.sh >/dev/null 2>&1

function on_new_shell() {
    # Set prompt PS1 to "user@host dir$ "
    export PS1='\u@\h \W\$ '

    # Set the virtual environment.
    if [ "$USE_VIRTUALENV" != "false" ]; then
        workon_walk

        if [ -d $PWD/.env ]; then
            . $PWD/.env/bin/activate
        fi
    fi

    # check the window size after each command and, if necessary,
    # update the values of LINES and COLUMNS.
    shopt -s checkwinsize

    receive /etc/bash_completion
    receive $BASH_DIR/bash_completion

    # Alias git completion to homegit script.
    complete -o default -o nospace -F _git homegit >/dev/null 2>&1
    complete -o default -o nospace -F _tig hometig >/dev/null 2>&1
}

# Avoid mangling the various PATHS on new bash invocations.
if [ -n "$BASHRC_INITIALIZED" ]; then
    on_new_shell
    return
fi

## PATH management.

# Set important paths.
prepend PATH /bin /sbin
prepend LD_LIBRARY_PATH /lib /lib32 /lib/i386-linux-gnu /lib64 /lib/x86_64-linux-gnu

prepend PATH /usr/bin /usr/sbin
prepend LD_LIBRARY_PATH /usr/lib /usr/lib32 /usr/lib/i386-linux-gnu /usr/lib64 /usr/lib/x86_64-linux-gnu
prepend MANPATH /usr/man /usr/share/man

prepend PATH /usr/local/bin /usr/local/sbin
prepend LD_LIBRARY_PATH /usr/local/lib /usr/local/lib32 /usr/local/lib/i386-linux-gnu /usr/local/lib64 /usr/local/lib/x86_64-linux-gnu
prepend MANPATH /usr/local/man /usr/local/share/man

prepend PATH /opt/local/bin /opt/local/sbin
prepend LD_LIBRARY_PATH /opt/local/lib /opt/local/lib32 /opt/local/lib64
prepend MANPATH /opt/local/man /opt/local/share/man

prepend PATH $HOME/bin
prepend LD_LIBRARY_PATH $HOME/lib $HOME/lib32 $HOME/lib64
prepend MANPATH $HOME/man $HOME/share/man

append PATH /opt/*/bin
append LD_LIBRARY_PATH /opt/*/lib /opt/*/lib32 /opt/*/lib64
append MANPATH /opt/*/man /opt/*/share/man

prepend PATH /opt/scala/bin
prepend LD_LIBRARY_PATH /opt/scala/lib /opt/scala/lib32 /opt/scala/lib64
prepend MANPATH /opt/scala/man /opt/scala/share/man

append PATH $HOME/sandbox/android/sdk/platform-tools
append PATH $HOME/sandbox/android/sdk/tools

append PATH $HOME/.*-dist/bin

export PATH
export LD_LIBRARY_PATH
export MANPATH

## ... and so on.

# Have bin/screen choose opt screen if installed.
ship SCREEN=/opt/screen/bin/screen
ship SCREENRC_DEFAULT=$HOME/.screenrc-default

# Set Android / Java defaults.
ship M2_HOME=/usr/share/maven2
ship M3_HOME=/opt/maven
ship ANDROID_HOME=/home/rduplain/sandbox/android/sdk
ship JAVA_HOME=/usr/lib/jvm/java-6-sun
ship IDEA_JDK=/usr/lib/jvm/jdk1.6.0_26

# Go language.
export GOPATH=$HOME/.go

# Set Python defaults.
ship PYTHONSTARTUP="$HOME/.pythonrc.py"
prepend PYTHONPATH $HOME/lib/python/site-packages
prepend PYTHONPATH $HOME/lib/python
export PYTHONPATH

# RVM for Ruby
# receive $HOME/.rvm/scripts/rvm
# rvm use ruby-1.8.7 > /dev/null 2>&1

function workon_walk () {
    # Walk the directory tree upward until:
    #  * a virtualenv is found which matches the name of a directory
    #  * the root directory is reached (no virtualenv found)
    #
    # Activate the identified virtualenv with virtualenvwrapper's workon.
    dir=${PWD}
    while [ -n "$dir" ]; do
        workon ${dir##*/} >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            break
        fi
        dir=${dir%/*}
    done
}

# Provide workon_walk to new shell invocations.
export -f workon_walk

# pydoc within a virtualenv
alias pydoc='python `which pydoc`'

# pip for Python
ship PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

on_new_shell

# If not running interactively, don't do anything further.
if [ -z "$PS1" ]; then
    return
fi

ship R_LIBS_USER=$HOME/.r

# Set editor and essential program defaults.
alias emacs='emacs -nw'

export EDITOR='emacs -nw'
export VISUAL=vi
export TEXEDIT=$EDITOR
export PAGER=less
export GZIP="-9"

# Set locale.
export LC_ALL=en_US.UTF-8

# Make less more friendly for non-text input files, see lesspipe(1).
[[ -x /usr/bin/lesspipe ]] && eval "$(lesspipe)"

# todo.txt
alias todo=todo.sh
alias t=todo.sh

# If this is an xterm set the title to "user@host dir"
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='history -a; echo -ne "\033]0;${USER}@${HOSTNAME} ${PWD/$HOME/~}\007"'
    ;;
*)
    PROMPT_COMMAND='history -a'
    ;;
esac
export PROMPT_COMMAND

# Enable color support of ls.
if [ "$TERM" != "dumb" ]; then
    if ( which dircolors >/dev/null 2>&1 ); then
        eval "`dircolors -b`"
        alias ls='ls --color=auto'
    fi
fi

# Don't put duplicate lines in the history. See bash(1) for more options.
export HISTCONTROL=ignoreboth
export HISTFILESIZE=9999
export HISTSIZE=20000
export FCEDIT=$EDITOR
export FIGNORE='~'
unset MAILCHECK MAILPATH
unset CDPATH

export WORKSPACES_RESERVED=5

function commands () {
    history | cut -c8- | sort | uniq -c | sort -rn | head
}

# Load a simple script with executes `export GITHUB_TOKEN=...`.
receive .gitconfig.github.sh

# Set a sentinel variable to the current time in seconds since epoch.
export BASHRC_INITIALIZED=`date +%s`
