#!/bin/sh

xset +fp $HOME/.local/share/fonts

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

exec ck-launch-session dbus-launch --autolaunch=444e9b7694df1a1f58655309536f0f3b --exit-with-session /opt/fluxbox/bin/startfluxbox
